apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    meta.helm.sh/release-name: openebs
    meta.helm.sh/release-namespace: openebs
  labels:
    app: openebs
    app.kubernetes.io/managed-by: Helm
    chart: openebs-3.10.0
    heritage: Helm
    release: openebs
  name: openebs
  namespace: openebs
